trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  JAVA_HOME: '/usr/lib/jvm/zulu-11-azure-amd64'
  MAVEN_OPTS: '-Xmx1024m'

steps:
# 1. Checkout del código desde GitHub
- checkout: self

# 2. Compilar la aplicación con Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'DiseñoBE/pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'clean package'
    options: '-DskipTests'
  displayName: 'Build Spring Boot Application'

# 3. Copiar el archivo JAR generado
- task: CopyFiles@2
  inputs:
    contents: '**/target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy JAR file'

# 4. Publicar el artefacto para el despliegue
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

# 5. Desplegar en Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'your-azure-subscription'
    appName: 'aiwoodworks-backend'
    package: '$(Build.ArtifactStagingDirectory)/*.jar'
  displayName: 'Deploy to Azure Web App'
