services:
  - type: web
    name: aiwoodworks-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: "./Diseño BE/backend/Dockerfile"
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar backend/target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:sqlserver://aiwoodworkssrvr.database.windows.net:1433;database=aiwoodworks_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
      - key: SPRING_DATASOURCE_USERNAME
        value: "asaraya@aiwoodworkssrvr"
      - key: SPRING_DATASOURCE_PASSWORD
        value: "Guachin321!"
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
