version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://aiwoodworkssrvr.database.windows.net:1433;database=aiwoodworks_db"
      SPRING_DATASOURCE_USERNAME: "asaraya@aiwoodworkssrvr"
      SPRING_DATASOURCE_PASSWORD: "Guachin321!"
      SPRING_DATASOURCE_ENCRYPT: "true"
      SPRING_DATASOURCE_TRUST_SERVER_CERTIFICATE: "false"
      SPRING_DATASOURCE_HOSTNAME_IN_CERTIFICATE: "*.database.windows.net"
      SPRING_DATASOURCE_LOGIN_TIMEOUT: "30"
    ports:
      - "8080:8080"
    volumes:
      - "C:/Users/kevin/Documents/TEC/2024/IIS/Diseno/Proyecto/AIWoodWorks/Diseño BE/backend/target/backend-0.0.1-SNAPSHOT.jar:/app/backend.jar"
      - "C:/Users/kevin/Documents/TEC/2024/IIS/Diseno/Proyecto/AIWoodWorks/Diseño BE/designs:/app/designs"  # Mounts designs directory
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
