name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio desde GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Java
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # 3. Asignar permisos de ejecución a `mvnw`
    - name: Grant execute permissions for Maven Wrapper
      run: chmod +x "Diseño BE/backend/mvnw"

    # 4. Compilar tu aplicación con Maven
    - name: Build with Maven
      working-directory: "Diseño BE/backend"
      run: ./mvnw clean package -DskipTests

    # 5. Construir la imagen Docker usando tu Dockerfile
    - name: Build Docker Image
      working-directory: "Diseño BE/backend"
      run: docker build -t aiwoodworks-backend -f Dockerfile .

    # 6. Ejecutar el contenedor Docker con credenciales explícitas
    - name: Run Docker Container
      run: |
        docker run -d -p 8080:8080 \
        -e SPRING_DATASOURCE_URL="jdbc:sqlserver://aiwoodworkssrvr.database.windows.net:1433;database=aiwoodworks_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;" \
        -e SPRING_DATASOURCE_USERNAME="asaraya@aiwoodworkssrvr" \
        -e SPRING_DATASOURCE_PASSWORD="Guachin321!" \
        -e SPRING_DATASOURCE_DRIVER_CLASS_NAME="com.microsoft.sqlserver.jdbc.SQLServerDriver" \
        aiwoodworks-backend
